name: prep_ng
description: "JAMB & WAEC Exam Preparation App for Nigerian Students"
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ^3.10.0-142.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  connectivity_plus: ^7.0.0
  local_auth: ^3.0.0
  video_player: ^2.9.1
  logger: ^2.0.2
  google_fonts: ^8.0.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  intl: ^0.20.2
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  cached_network_image: ^3.3.1
  flutter_paystack_plus: ^2.4.0
  http: ^1.1.2
  firebase_messaging: 16.1.1
  flutter_local_notifications: ^17.0.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
  - assets/images/prepnglogo.png
  - assets/images/bookillustration1.1.png
  - assets/images/bookillustration2.png
  - assets/images/bookillustration3.jpg
  - assets/images/bookillustration4.jpg
  - assets/images/boy on graduation-bro.png
  - assets/images/disabled student-bro.png
  - assets/images/Exams-bro.png
  - assets/images/girl on graduation-bro.png
  - assets/images/Raising hand-bro.png
  - assets/images/Student stress-bro.png

flutter_launcher_icons:
  image_path: "assets/images/prepnglogo.png"
  android: "lancher_icon"
  ios: false
  min_sdk_android:
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/prepnglogo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/prepnglogo.png
  android: true
  ios: false
  android_12:
    color: "#000000"
    image: assets/images/prepnglogo.png
    icon_background_color: "#000000"